2023-10-12 11:31:43,141 INFO Scheduler started
2023-10-12 11:31:43,667 INFO Start creating a new auth key on DC2
2023-10-12 11:31:43,667 INFO Connecting...
2023-10-12 11:31:43,734 INFO Connected! Production DC2 - IPv4
2023-10-12 11:31:45,041 INFO Done auth key exchange: DhGenOk
2023-10-12 11:31:45,041 INFO Disconnected
2023-10-12 11:31:45,064 INFO Connecting...
2023-10-12 11:31:45,127 INFO Connected! Production DC2 - IPv4
2023-10-12 11:31:45,132 INFO NetworkTask started
2023-10-12 11:31:45,509 INFO Session initialized: Layer 158
2023-10-12 11:31:45,509 INFO Device: CPython 3.11.4 - Pyrogram 2.0.106
2023-10-12 11:31:45,509 INFO System: Linux 6.2.0-34-generic (en)
2023-10-12 11:31:45,509 INFO Session started
2023-10-12 11:31:45,511 INFO PingTask started
2023-10-12 11:31:45,667 ERROR Telegram says: [401 AUTH_KEY_UNREGISTERED] - The key is not registered in the system. Delete your session file and login again (caused by "updates.GetState")
Traceback (most recent call last):
  File "/app/main.py", line 16, in main
    await app.initialize_pyrogram()
  File "/app/src/client.py", line 30, in initialize_pyrogram
    await self.client.invoke(raw.functions.updates.GetState())
  File "/usr/local/lib/python3.11/site-packages/pyrogram/methods/advanced/invoke.py", line 79, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyrogram/session/session.py", line 389, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyrogram/session/session.py", line 357, in send
    RPCError.raise_it(result, type(data))
  File "/usr/local/lib/python3.11/site-packages/pyrogram/errors/rpc_error.py", line 91, in raise_it
    raise getattr(
pyrogram.errors.exceptions.unauthorized_401.AuthKeyUnregistered: Telegram says: [401 AUTH_KEY_UNREGISTERED] - The key is not registered in the system. Delete your session file and login again (caused by "updates.GetState")
